# Generated by Django 5.1.2 on 2024-10-31 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalActivities',
            fields=[
                ('practical_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('practical_name', models.CharField(default='Practical', max_length=100)),
                ('grade_level', models.CharField(default='1', max_length=20)),
                ('duration', models.DurationField()),
                ('instruction', models.TextField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_file', models.FileField(default='practical_videos/default_video.mp4', upload_to='practical_videos/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
