# Generated by Django 5.1.2 on 2024-10-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=100)),
                ('school_status', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
            ],
        ),
    ]
