# Generated by Django 5.1.2 on 2024-10-31 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practical_activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('practical_title', models.CharField(max_length=50)),
                ('description', models.CharField(default='Default description', max_length=255)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade_level', models.CharField(default='1', max_length=20)),
                ('points', models.BigIntegerField()),
                ('practical_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practical_activities.practicalactivities')),
            ],
        ),
    ]
