# Generated by Django 5.1.2 on 2024-10-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(default='unknown', max_length=20)),
                ('password', models.CharField(default='default_password', max_length=128)),
                ('school_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
            ],
        ),
    ]
